### ISSUE TITLE
Crash after update 1.0.2_beta.2-1 -> 1.0.2_beta.2-2 Archlinux

### ISSUE THREAD

**Issue by Ades128** [pierr3/TrackAudio#30]
Encounter crash passed few seconds after launch without doing anything.

Using Trackaudio on Arch linux.
Kernel 6.8.8-arch1-1
same issue using either trackaudio-bin or trackaudio-git trough AUR package
Appear after updating 1.0.2_beta.2-1 -> 1.0.2_beta.2-2

```
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x78D308C006C0!
Segmentation fault (core dumped)
```

Backtrace from the dumpcorectl

```
(gdb) bt full
#0  0x00007de10660fd30 in RemoteData::getSlurperData[abi:cxx11]() () at /tmp/.org.chromium.Chromium.aEM7KA
#1  0x00007de1066103cd in RemoteData::onTimer(Poco::Timer&) () at /tmp/.org.chromium.Chromium.aEM7KA
#2  0x00007de106675be7 in Poco::Timer::run() () at /tmp/.org.chromium.Chromium.aEM7KA
#3  0x00007de10667d6af in Poco::PooledThread::run() () at /tmp/.org.chromium.Chromium.aEM7KA
#4  0x00007de106680731 in Poco::ThreadImpl::runnableEntry(void*) () at /tmp/.org.chromium.Chromium.aEM7KA
#5  0x00007de198e3355a in start_thread (arg=<optimized out>) at pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {138405239326400, 7608232385281972051, -1144, 2, 140724935023184, 138405230936064, -7902646139699407021, -7901865931133626541}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007de198eb0a5c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by pierr3** [comment]
Thank you for the back trace, i’ll take a look

**Comment by Ades128** [comment]
Hi, i try the new commit d98825769d1cbbdb64710269f7f13a38adf51907 via AUR package.

Initial crash is solved, thanks, but now i receive this "notification"
```
[1855Z] Error while parsing slurper data, check the log file. This means your internet may be down or the VATSIM servers may experience an outage. You will not be able to connect until this is resolved. TrackAudio will keep retrying in the background.
```

Log:
```
20:49:54.776826689 [22561] RemoteData.hpp:57            LOG_ERROR     trackaudio_logger Cannot get data from the slurper. Object is null.
```
https://slurper.vatsim.net/users/info/?cid=1572048 is:
```
1572048,LFMN__APP,atc,134.475,120,43.66541,7.21498,0,0,0,0,0,0,0,0,
```
Also tested using VectorAudio, works well.

**Comment by Ades128** [comment]
no change after b195052.

**Comment by Ades128** [comment]
For me with the last commit the crash is solved
